BACK/nest-app/.eslintrc.js
BACK/nest-app/.gitignore
BACK/nest-app/.prettierrc
BACK/nest-app/README.md
BACK/nest-app/nest-cli.json
BACK/nest-app/package-lock.json
BACK/nest-app/package.json
BACK/nest-app/prisma/schema.prisma
BACK/nest-app/src/app.controller.spec.ts
BACK/nest-app/src/app.controller.ts
BACK/nest-app/src/app.module.ts
BACK/nest-app/src/app.service.ts
BACK/nest-app/src/main.ts
BACK/nest-app/test/app.e2e-spec.ts
BACK/nest-app/test/jest-e2e.json
BACK/nest-app/tsconfig.build.json
BACK/nest-app/tsconfig.json

NestJs 애플리케이션을 위한 패키지 설정을 완료하였습니다.
#2

Nest project setting(#2)

---

FRONT/package-lock.json
FRONT/package.json

styled-components package 설정
- styled-components package 설정

styled-components package 설정

---

FRONT/src/assets/icons/left-arrow.svg
FRONT/src/assets/icons/right-arrow.svg
FRONT/src/components/PagingButton/PagingButton.styles.ts
FRONT/src/components/PagingButton/PagingButton.tsx

PagingButton 컴포넌트 추가
- left-arrow, right-arrow 아이콘 추가
- PagingButton 컴포넌트 구현
- currentPage <= 5면 왼쪽 화살표가 표시 안 됨, 더 이상 이동할 수 없으면  오른쪽 화살표가 표시 안 됨
- 화살표를 클릭하면 다음/이전 5개씩 페이지 이동할 수 있도록 했음
- 테스트 코드를 작성하지 않았음
#5  
테스트 하려면 
```
const [currentPage, setCurrentPage] = useState(1);
<PagingButton
totalPages={8}
currentPage={currentPage}
setCurrentPage={setCurrentPage}
/>
```
이런 식으로 값을 전달하시면 돼요
화면 캡쳐 이미지:

PagingButton 컴포넌트 추가(#5)

---

FRONT/src/components/PagingButton/PagingButton.style.ts
FRONT/src/components/PagingButton/PagingButton.tsx

화살표를 누를 때 숫자가 움직여서 불편하기 때문에 ArrowBtn 스타일을 수정했음
- 1자리 숫자와 2자리 숫자의 크기가 달라서 숫자의 width 25px로 고정 시킴
- ArrowButton의 속성에 visibility를 추가하여 맨 처음/ 맨마지막 화살표가 안 보이도록 했음
Related #5

ArrowBtn 스타일 수정

---

BACK/nest-app/prisma/schema.prisma
BACK/nest-app/src/app.module.ts
BACK/nest-app/src/category/category.module.ts
BACK/nest-app/src/category/category.service.spec.ts
BACK/nest-app/src/category/category.service.ts
BACK/nest-app/src/post/post.controller.spec.ts
BACK/nest-app/src/post/post.controller.ts
BACK/nest-app/src/post/post.module.ts
BACK/nest-app/src/post/post.service.spec.ts
BACK/nest-app/src/post/post.service.ts
BACK/nest-app/src/prisma/prisma.module.ts
BACK/nest-app/src/prisma/prisma.service.spec.ts
BACK/nest-app/src/prisma/prisma.service.ts

- 카테고리별 게시글 조회 API 구현을 완료하였습니다.
- 페이징 적용에 대한 상의가 필요합니다.
#5

카테고리별 게시글 조회 API 구현 완료 (#5)

---

FRONT/src/App.css
FRONT/src/App.tsx
FRONT/src/components/Button/Button.style.ts
FRONT/src/components/Button/Button.tsx
FRONT/src/pages/Home/Home.tsx
FRONT/src/pages/Home/components/PostItem/PostItem.style.ts
FRONT/src/types/aliases.d.ts
FRONT/tests/setup.ts
FRONT/tsconfig.json
FRONT/vite.config.ts

각자 작성한 여러 컴포넌트 파일을 Home 페이지에 레이아웃 구현하여 합쳤습니다.
- 모든 요소에 적용돼있던 스타일 html, body로 수정
- 반응형 폰트 추가
- `App` 컴포넌트에 `Navbar`, `Footer` 추가
- `PagingButton` 추가 및 페이지 상태 추가
- assets 폴더 절대경로 설정
- 불필요한 코드 라인 삭제 및 스타일 수정
Related to #5 
- [페이지 디자인 링크](https://www.figma.com/design/koMuWZezrWmiFz5YNBzz0M/Starchive?node-id=4-3&t=G1VTA8B50EDx52z3-4) <- 디자인의 태그 부분은 구현 이후에 추가된 거라서 현재 PR에는 누락돼있습니다.
- 지금은 static하게 `PostItem` 컴포넌트를 넣었는데, 나중에 public에 mockdata 생성해서 테스트 해보겠습니다. (일단은 화면만 ㅎㅎ)

메인 게시글 목록 페이지 레이아웃 (#5)

---

FRONT/src/App.tsx
FRONT/src/components/Aside/Aside.style.ts
FRONT/src/components/Aside/Aside.tsx
FRONT/src/components/Aside/components/CategoryNode.style.ts
FRONT/src/components/Aside/components/CategoryNode.tsx
FRONT/src/components/Aside/components/useCategoryNode.ts
FRONT/src/components/Aside/types/Category.ts
FRONT/src/components/Aside/types/category.ts
FRONT/src/components/Aside/useAside.ts
FRONT/src/components/Navbar/Navbar.tsx

Aside 컴포넌트 기능 구현 및 리팩토링
- [Navbar에 Aside 컴포넌트 연결](https://github.com/DevBadgers/starchive/commit/1c766dd1f1cc2e59c750cdf466bdfc069478f1bc)
- [카테고리 클릭 시 해당 글 목록 페이지로 이동 구현](https://github.com/DevBadgers/starchive/commit/5052483eeafa5ee3d4b003ceeb69f7f81339bced)
- 리팩토링
Related #5 
refactor랑 feature 둘 다 한 PR에 해도될지 모르겠는데 일단 올립니다ㅜ!

Aside 컴포넌트 기능 구현 및 리팩토링 (#5)

---

BACK/spring-app/.gitignore
BACK/spring-app/build.gradle
BACK/spring-app/src/main/java/com/starchive/springapp/global/dto/ResponseDto.java
BACK/spring-app/src/main/java/com/starchive/springapp/global/exception/GlobalExceptionHandler.java
BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/controller/HashTagController.java
BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/domain/HashTag.java
BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/dto/HashTagDto.java
BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/dto/HashTagRequest.java
BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/exception/HashTagNotFoundException.java
BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/repository/HashTagRepository.java
BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/service/HashTagService.java
BACK/spring-app/src/test/java/com/starchive/springapp/hashtag/controller/HashTagControllerTest.java
BACK/spring-app/src/test/java/com/starchive/springapp/hashtag/service/HashTagServiceTest.java

해쉬태그 조회 API 구현 완료했습니다.
- 해쉬태그 조회 및 생성 기능
- 해쉬태그 전체 조회 기능
- 테스트 코드 작성
- 스웨거 추가
#5

해쉬태그 조회 API 구현 (#5)

---

BACK/spring-app/.gitignore
BACK/spring-app/build.gradle
BACK/spring-app/src/main/java/com/starchive/springapp/category/controller/CategoryController.java
BACK/spring-app/src/main/java/com/starchive/springapp/category/domain/Category.java
BACK/spring-app/src/main/java/com/starchive/springapp/category/exception/CategoryNotFoundException.java
BACK/spring-app/src/main/java/com/starchive/springapp/global/dto/ResponseDto.java
BACK/spring-app/src/main/java/com/starchive/springapp/global/exception/GlobalExceptionHandler.java
BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/controller/HashTagController.java
BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/domain/HashTag.java
BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/dto/HashTagDto.java
BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/dto/HashTagRequest.java
BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/exception/HashTagNotFoundException.java
BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/repository/HashTagRepository.java
BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/service/HashTagService.java
BACK/spring-app/src/main/java/com/starchive/springapp/post/Post.java
BACK/spring-app/src/main/java/com/starchive/springapp/posthashtag/PostHashTag.java
BACK/spring-app/src/test/java/com/starchive/springapp/category/controller/CategoryControllerTest.java
BACK/spring-app/src/test/java/com/starchive/springapp/hashtag/controller/HashTagControllerTest.java
BACK/spring-app/src/test/java/com/starchive/springapp/hashtag/repository/HashTagRepositoryTest.java
BACK/spring-app/src/test/java/com/starchive/springapp/hashtag/service/HashTagServiceTest.java

특정 카테고리에 해당하는 해쉬태그 목록 조회하는 api 구현 완료했어요.
- 패스 파라미터로 categoryId를 받아서 해당하는 해쉬태그 목록을 반환합니다.
#5

특정 카테고리에 해당하는 해쉬태그 목록 조회 (#5)

---

BACK/nest-app/prisma/schema.prisma
BACK/nest-app/src/post/post.controller.ts
BACK/nest-app/src/post/post.service.ts

게시글 조회 API에 쿼리 파라미터를 이용해 페이징을 사용할 수 있도록 추가했습니다.
- 게시글 조회 API에 페이징 기능 추가
#5

게시글 조회에 페이징 추가 (#5)

---

FRONT/src/components/TagWrapper/TagWrapper.tsx
FRONT/src/components/TagWrapper/useTag.ts
FRONT/src/pages/Home/Home.tsx
FRONT/src/services/tagApi.ts
FRONT/src/types/tag.d.ts

카테고리별 태그리스트 조회 기능 구현
- 카테고리별 태그리스트 조회 기능 구현
Related to #5

카테고리별 태그리스트 조회 기능 구현 (#5)

---

FRONT/src/components/TagWrapper/useTag.ts
FRONT/src/services/postApi.ts
FRONT/src/services/tagApi.ts

태그별 글 목록 조회 api 수정
- 태그별 글 목록 조회 api를 잘못해서 지금 수정했음

태그별 글 목록 조회 api 수정

---

FRONT/src/pages/Home/Home.tsx
FRONT/src/pages/Home/components/PostItem/PostItem.style.ts
FRONT/src/pages/Home/components/PostItem/PostItem.tsx
FRONT/src/types/post.d.ts

- 포스트 하단에 해시태그 표시
- PostItem의 categoryHier 타입을 단일 객체를 포함하는 배열인 [{...}]에서 다수 객체를 포함할 수 있는 배열인 {...}[]으로 수정
Related to #5

포스트 하단에 해시태그 표시 (#5)

---

FRONT/src/App.tsx
FRONT/src/assets/icons/drop-down-icon.svg
FRONT/src/components/Footer/Footer.style.ts
FRONT/src/pages/CreatePost/CreatePost.style.ts
FRONT/src/pages/CreatePost/CreatePost.tsx
FRONT/src/pages/CreatePost/components/CategorySelector/CategorySelector.style.ts
FRONT/src/pages/CreatePost/components/CategorySelector/CategorySelector.tsx

글 작성 페이지 레이아웃 구현
- Footer을 하단에서 고정시켰음
- CategorySelector 컴포넨트: api 호출해서 전체 카테고리 넣고, 카테고리 선택하면 console.log에 id 출력
- 입력칸 구현
Related #4

글 작성 페이지 레이아웃(#4)

---

BACK/spring-app/src/main/java/com/starchive/springapp/global/config/WebConfig.java

모든 응답 헤더에 cors 헤더 추가
- "https://starchive.vercel.app"로 부터 오는 요청 허용

cors 헤더 추가

---

BACK/spring-app/src/main/resources/application.properties

main 브랜치에 스프링 환경 설정 파일이 남아있어서 삭제 했어요.
- application.properties 파일 삭제

스프링 설정 파일 삭제

---

FRONT/package-lock.json
FRONT/package.json
FRONT/src/App.css
FRONT/src/assets/icons/add-photo.svg
FRONT/src/assets/icons/align-center.svg
FRONT/src/assets/icons/align-left.svg
FRONT/src/assets/icons/align-right.svg
FRONT/src/components/Footer/Footer.style.ts
FRONT/src/index.css
FRONT/src/pages/CreatePost/CreatePost.style.ts
FRONT/src/pages/CreatePost/CreatePost.tsx
FRONT/src/pages/CreatePost/components/CategorySelector/CategorySelector.tsx
FRONT/src/pages/CreatePost/components/EditorContainer/EditorContainer.style.ts
FRONT/src/pages/CreatePost/components/EditorContainer/EditorContainer.tsx
FRONT/src/pages/CreatePost/components/NicknamePasswordInput/NicknamePasswordInput.style.ts
FRONT/src/pages/CreatePost/components/NicknamePasswordInput/NicknamePasswordInput.tsx

마크다운 작성 기능
- 마크다운 작성, 프리뷰 기능 구현
- Editor와 Preview의 높이가 작성하는대로 늘려지게하기위해서 FooterContainer의 position: fixed를 제거했어요
Related to #4 
EditorContainer.tsx에서 components(line:52)를 renderCodeBlock(line:18)로 분리했는데, 시인성 측면에서 지금처럼 분리해두는게 나을지, 합치는게 나을지, 아니면 아예 다른 파일로 빼는게 나을지 모르겠습니다

마크다운 작성 기능 (#4)

---

.github/workflows/spring-delploy.yml
.github/workflows/spring-integration.yml

깃 허브 액션 CICD 수정했어요
- CI 실행 시 application-test.properties 를 깃 허브 액션 Runner에 생성 후 테스트 코드를 실행하도록 변경
- CD 실행 시 application-test.properties 와 application-prod.properties 파일을 Runner에 생성 후 scp로 ec2에 배포 되도록 기능 추가

깃 허브 액션 수정

---

BACK/spring-app/src/main/java/com/starchive/springapp/global/config/WebConfig.java

cors 허용 경로 수정

---

FRONT/src/pages/CreatePost/components/MarkdownEditor/MarkdownEditor.style.ts
FRONT/src/pages/CreatePost/components/MarkdownEditor/MarkdownEditor.tsx
FRONT/src/pages/CreatePost/components/MarkdownEditor/useMarkdownEditor.ts
FRONT/src/pages/CreatePost/components/ToolBar/ToolBar.tsx
FRONT/src/services/api.ts
FRONT/src/services/categoryApi.ts
FRONT/src/services/createPostApi.ts
FRONT/src/services/tagApi.ts

사진 업로드 api 연동
- addPhotoIcon 클릭할 때 useRef를 통해 <input> file 열림
- handleAddPhotoClick 함수를 props로 전달
- postImage : 사진 업로드 api 구현
- hook에서 handleFileChange: api 호출하고 나서 그 경로를 markdown에서 넣었음
- 사진 url 도착하기전 "Uploading...." 표시
Related #4

사진 업로드 api 연동(#4)

---

FRONT/src/pages/CreatePost/CreatePost.tsx
FRONT/src/pages/CreatePost/components/TagWrapper/TagWrapper.tsx
FRONT/src/pages/CreatePost/hooks/useCreatePost.ts
FRONT/src/pages/CreatePost/hooks/useTag.ts
FRONT/src/services/tagApi.ts

태그 저장 로직 추가
- TagWrapper에서 태그 관련 상태와 함수들을 useTag 훅으로 분리
- handleSaveButtonClick에 태그 저장 로직 포함
Related to #4

태그 저장 로직 추가 (#4)

---

BACK/spring-app/src/main/java/com/starchive/springapp/category/dto/CategorySimpleDto.java
BACK/spring-app/src/main/java/com/starchive/springapp/category/repository/CategoryRepository.java
BACK/spring-app/src/main/java/com/starchive/springapp/category/service/CategoryService.java
BACK/spring-app/src/main/java/com/starchive/springapp/global/ErrorMessage.java
BACK/spring-app/src/main/java/com/starchive/springapp/global/exception/GlobalExceptionHandler.java
BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/dto/HashTagResponse.java
BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/repository/HashTagRepository.java
BACK/spring-app/src/main/java/com/starchive/springapp/hashtag/service/HashTagService.java
BACK/spring-app/src/main/java/com/starchive/springapp/post/controller/PostController.java
BACK/spring-app/src/main/java/com/starchive/springapp/post/dto/PostDto.java
BACK/spring-app/src/main/java/com/starchive/springapp/post/dto/PostListResponse.java
BACK/spring-app/src/main/java/com/starchive/springapp/post/exception/PostNotFoundException.java
BACK/spring-app/src/main/java/com/starchive/springapp/post/repository/PostRepository.java
BACK/spring-app/src/main/java/com/starchive/springapp/post/service/PostService.java
BACK/spring-app/src/main/java/com/starchive/springapp/posthashtag/domain/PostHashTag.java
BACK/spring-app/src/main/java/com/starchive/springapp/posthashtag/service/PostHashTagService.java
BACK/spring-app/src/test/java/com/starchive/springapp/post/service/PostServiceTest.java

- 게시글 전체 조회 기능 구현
- 쿼리파라미터로 categoryId, hashTagId, pageNum, pageSize 입력
- pageNum 디폴트 값 0, pageSize 디폴트 값 10
Refs: #5

게시글 전체 조회 (#5)

---

FRONT/src/App.tsx
FRONT/src/components/TagWrapper/useTag.ts
FRONT/src/pages/Home/Home.tsx
FRONT/src/pages/Home/components/PostItem/PostItem.style.ts
FRONT/src/pages/Home/components/PostItem/PostItem.tsx
FRONT/src/pages/Post/Post.style.ts
FRONT/src/pages/Post/Post.tsx
FRONT/src/services/postApi.ts
FRONT/src/types/aliases.d.ts
FRONT/src/types/post.d.ts
FRONT/vite.config.ts

- 게시글 상세 조회 api 연동
- 게시글 조회 페이지 레이아웃 수정
- aliases @_types 선언
- Post interface와 Post 페이지 이름 충돌되서 타입 이름 Post -> PostParams 바꿨음
- Home페이지에서 PostItem의 카테고리가 2줄으로 잘려되어 버려서 스타일 수정했음
- 게시글 상세 조회 api 연동했음
Closed #6

게시글 상세 조회 api 연동(#6)

---

FRONT/src/components/TagWrapper/useTag.ts
FRONT/src/pages/Home/Home.tsx

페이징 버그 수정
- PagingButton는 1부터 시작하는데 api 요청할 때 0번 페이지와 해당되어야 해요
- totalPages는 훅으로부터 받아서 전달했음
Closed #69

페이징 버그 수정(#69)

---

FRONT/src/components/Aside/Aside.tsx
FRONT/src/components/Aside/useAside.ts
FRONT/src/pages/CreatePost/components/CategorySelector/CategorySelector.tsx

- aside에서 카테고리가 없는 게시글 조회하는 ‘기타’ 버튼 추가
- 게시글을 생성할 때 ‘카테고리 없음’ 추가, categoryId = 0로 보내기
Related #8

카테고리 없은 게시글 조회(#8)

---

.github/workflows/spring-delploy.yml

feat: 브랜치 구별해서 배포 되도록 수정

---

FRONT/src/components/IconButton/IconButton.tsx
FRONT/src/pages/MyPage/components/CategoryManagement/CategoryManagement.style.ts
FRONT/src/pages/MyPage/components/CategoryManagement/CategoryManagement.tsx
FRONT/src/pages/MyPage/components/CategoryNode/CategoryNode.style.ts
FRONT/src/pages/MyPage/components/CategoryNode/CategoryNode.tsx
FRONT/src/pages/MyPage/hooks/useCategoryManagement.ts
FRONT/src/services/categoryApi.ts

카테고리 관리 기능
- 카테고리 수정,삭제,추가 기능
Related to #8

카테고리 관리 기능 (#8)

---

FRONT/src/pages/CreatePost/components/CategorySelector/CategorySelector.style.ts
FRONT/src/pages/CreatePost/components/CategorySelector/CategorySelector.tsx

"카테고리 없음" 중복 문제 해결
- 중복된 '카테고리 없음' 항목을 하나로 통일
- 하위 카테고리가 있는 경우에만 드롭다운 아이콘이 렌더링되도록 수정
Related to #81

"카테고리 없음" 중복 문제 해결 (#81)
